manifest:
  remotes:
    - name: muhannad
      url-base: https://github.com/muhannad-hash
  projects:
    - name: zmk
      remote: muhannad
      revision: main 
      import: app/west.yml
  self:
    path: config